[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build --workspace=aba-payway-sdk-unofficial",
  "npm run build --workspace=api"
]

[start]
cmd = "npm run start --workspace=api"
